const enc = new TextEncoder();
async function sha256Hex(input){const data=typeof input==="string"?enc.encode(input):input;const hash=await crypto.subtle.digest("SHA-256",data);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function hmacSha256Hex(secret,message){const key=await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("HMAC",key,enc.encode(message));return [...new Uint8Array(sig)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function canon(obj){if(Array.isArray(obj))return"["+obj.map(canon).join(",")+"]";if(obj&&typeof obj==="object")return"{"+Object.keys(obj).sort().map(k=>JSON.stringify(k)+":"+canon(obj[k])).join(",")+"}";return JSON.stringify(obj)}
const DEFAULT_CATEGORY_MAP={schema:"arc.seedcatalog.category_map.v1",version:"0.7.0",fallback_category:"catalog/authorized/uncategorized",mappings:{movie:"media/movie/authorized",show:"media/show/authorized","public-domain":"media/public-domain/authorized",internal:"asset/internal/authorized",game:"game/homebrew/authorized"}};
const RULESET={schema:"arc.seedcatalog.ruleset.v7",version:"0.7.0",store_raw_names:false,store_raw_urls:false,store_server_names:false,store_paths:false,store_user_data:false};
function cat(raw){const s=String(raw||"").toLowerCase().replaceAll(" ","-");return DEFAULT_CATEGORY_MAP.mappings[s]||(`catalog/authorized/${s||"uncategorized"}`)}
function rows(doc){if(Array.isArray(doc))return doc;let out=[];if(doc&&Array.isArray(doc.servers)){for(const srv of doc.servers){for(const it of (srv.items||[])){out.push({...it,_server_id:srv.server_id||"source",_server_type:srv.server_type||"authorized_catalog",_region:srv.region||"unknown",_legal_basis:srv.legal_basis||"authorized_or_internal"})}}}else if(doc&&Array.isArray(doc.data))out=doc.data;return out}
async function buildSplitBundles(doc,seed,epoch){const receipts=[],rh=await sha256Hex("arc.seedcatalog.ruleset.v7"),cmh=await sha256Hex("category-map-v7"),ah=await sha256Hex("adapter-v7");for(const it of rows(doc)){const c=cat(it.category),sf=JSON.stringify({server_type:it._server_type||it.type||"authorized_catalog",region:it._region||"unknown",legal_basis:it._legal_basis||"authorized_or_internal"}),sid=await sha256Hex(sf),vol=`${it._server_id||it.server||"source"}|${it.path||it.url||it.id||""}|${it.title||it.name||""}|${epoch}`,core={schema:"arc.seedcatalog.entry_receipt.v7",entry_id:"hmac-sha256:"+await hmacSha256Hex(seed,sid+"|"+vol),source_id:"sha256:"+sid,category_vector:"hmac-sha256:"+await hmacSha256Hex(seed,c+"|"+rh+"|"+cmh),category_path_hash:"sha256:"+await sha256Hex(c),ruleset_hash:"sha256:"+rh,category_map_hash:"sha256:"+cmh,adapter_profile_hash:"sha256:"+ah,epoch,stored_raw_data:false,stores_title:false,stores_path:false,stores_server_name:false,stores_url:false,stores_user_data:false};receipts.push({...core,receipt_hash:"sha256:"+await sha256Hex(canon(core))})}const rb={schema:"arc.seedcatalog.receipt_bundle.v7",count:receipts.length,receipts,stores_raw_data:false};rb.bundle_hash="sha256:"+await sha256Hex(canon(rb));const records=receipts.map(r=>({schema:"arc.core.seedcatalog_registration.v7",source:"arc-seedcatalog",object_type:"seedcatalog_entry_receipt",receipt_hash:r.receipt_hash,entry_id:r.entry_id,source_id:r.source_id,category_vector:r.category_vector,category_path_hash:r.category_path_hash,ruleset_hash:r.ruleset_hash,category_map_hash:r.category_map_hash,adapter_profile_hash:r.adapter_profile_hash,stores_raw_data:false}));const ac={schema:"arc.core.seedcatalog_handoff_bundle.v7",records,entry_count:records.length,stores_raw_data:false};ac.bundle_hash="sha256:"+await sha256Hex(canon(ac));const split={schema:"arc.seedcatalog.split_bundle.v7",receipt_bundle:rb,arc_core_handoff_bundle:ac,signature_envelope:{status:"unsigned",signing_algorithm:"ed25519-planned",stores_raw_data:false},stores_raw_data:false};split.catalog_hash="sha256:"+await sha256Hex(canon(split));return split}
function arcCoreJSONL(split){return split.arc_core_handoff_bundle.records.map(r=>JSON.stringify(r)).join("\n")+"\n"}function proofPack(split){return{schema:"arc.seedcatalog.proof_pack.v7",split_bundle:split,stores_raw_data:false}}async function verifySplitBundle(split){return{schema:"arc.seedcatalog.verify_report.v7",ok:split.stores_raw_data===false&&split.receipt_bundle.stores_raw_data===false,catalog_hash:split.catalog_hash,entries:split.receipt_bundle.count}}
window.ARCSeedCatalog={buildSplitBundles,verifySplitBundle,arcCoreJSONL,proofPack,canon};
